-- =====================================================
-- CORRIGIR "Invalid schema: public" - EXECUTE TUDO NO SQL EDITOR
-- =====================================================
-- Supabase Dashboard > SQL Editor > New query > Cole > Run
-- Projeto: seminariosebitam (vwruogwdtbsareighmoc)
--
-- Se o passo 1 der erro de permissão, pule e execute só do passo 2 em diante.
-- O app já foi ajustado para não enviar schema; isso também evita o erro.

-- 1) PostgREST: expor o schema public (resolve "Invalid schema: public")
ALTER ROLE authenticator SET pgrst.db_schemas = 'public';

-- 2) Role anon deve poder usar o schema public
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;

-- 3) Criar tabelas se não existirem
CREATE TABLE IF NOT EXISTS public.estudantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    module INTEGER DEFAULT 1,
    grade INTEGER DEFAULT 1,
    plan TEXT DEFAULT 'integral',
    subject_grades JSONB DEFAULT '{}'::jsonb,
    subject_freqs JSONB DEFAULT '{}'::jsonb,
    payment_status TEXT DEFAULT 'Pendente',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.professores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    extra TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.administradores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    extra TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.secretarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    extra TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4) Permissões para anon (app usa chave anon)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.estudantes TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.professores TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.administradores TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.secretarias TO anon;

-- 5) Sequências (IDs automáticos)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;

-- 6) Desabilitar RLS para o app funcionar sem políticas
ALTER TABLE public.estudantes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.professores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.administradores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.secretarias DISABLE ROW LEVEL SECURITY;

-- 7) Garantir que novas tabelas também deem permissão ao anon (opcional)
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO anon;
