-- =====================================================
-- CRIAR TABELAS (se não existirem) + PERMISSÕES
-- =====================================================
-- Execute no SQL Editor do Supabase: New query > Cole tudo > Run
-- Projeto: seminariosebitam

-- 1. Permitir que a role anon use o schema public
GRANT USAGE ON SCHEMA public TO anon;

-- 2. Criar tabelas (só cria se ainda não existirem)
CREATE TABLE IF NOT EXISTS public.estudantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    module INTEGER DEFAULT 1,
    grade INTEGER DEFAULT 1,
    plan TEXT DEFAULT 'integral',
    subject_grades JSONB DEFAULT '{}'::jsonb,
    subject_freqs JSONB DEFAULT '{}'::jsonb,
    payment_status TEXT DEFAULT 'Pendente',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.professores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    extra TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.administradores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    extra TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.secretarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    extra TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Permissões para a role anon (app usa chave anon)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.estudantes TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.professores TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.administradores TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.secretarias TO anon;

-- 4. Sequências (para IDs automáticos)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;

-- 5. Desabilitar RLS para o app funcionar sem políticas
ALTER TABLE public.estudantes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.professores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.administradores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.secretarias DISABLE ROW LEVEL SECURITY;
