-- =====================================================
-- SEBITAM - DATABASE SETUP (VERSÃO CORRIGIDA)
-- =====================================================
-- Execute este script no SQL Editor do seu projeto Supabase
-- URL do Projeto: https://vwruogwdtbsareighmoc.supabase.co

-- IMPORTANTE: Execute TODO este script de uma vez só!

-- 1. Remover tabelas antigas se existirem (para recomeçar limpo)
DROP TABLE IF EXISTS estudantes CASCADE;
DROP TABLE IF EXISTS professores CASCADE;
DROP TABLE IF EXISTS administradores CASCADE;
DROP TABLE IF EXISTS secretarias CASCADE;

-- 2. Tabela de Estudantes (Alunos)
CREATE TABLE estudantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    module INTEGER DEFAULT 1,
    grade INTEGER DEFAULT 1,
    plan TEXT DEFAULT 'integral',
    subject_grades JSONB DEFAULT '{}'::jsonb,
    subject_freqs JSONB DEFAULT '{}'::jsonb,
    payment_status TEXT DEFAULT 'Pendente',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Professores
CREATE TABLE professores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    extra TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Administradores
CREATE TABLE administradores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    extra TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabela de Secretarias (SEM ACENTO!)
CREATE TABLE secretarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    extra TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Desabilitar RLS (Row Level Security) para facilitar testes
ALTER TABLE estudantes DISABLE ROW LEVEL SECURITY;
ALTER TABLE professores DISABLE ROW LEVEL SECURITY;
ALTER TABLE administradores DISABLE ROW LEVEL SECURITY;
ALTER TABLE secretarias DISABLE ROW LEVEL SECURITY;

-- 7. Criar índices para melhor performance
CREATE INDEX idx_estudantes_email ON estudantes(email);
CREATE INDEX idx_estudantes_grade ON estudantes(grade);
CREATE INDEX idx_professores_email ON professores(email);
CREATE INDEX idx_administradores_email ON administradores(email);
CREATE INDEX idx_secretarias_email ON secretarias(email);

-- 8. Inserir Super Admin automaticamente
INSERT INTO administradores (name, email, phone, extra)
VALUES ('Luiz Eduardo Santos da Silva', 'edukadoshmda@gmail.com', 'Gestor', 'Diretor Geral')
ON CONFLICT DO NOTHING;

-- Verificação: Listar todas as tabelas criadas
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('estudantes', 'professores', 'administradores', 'secretarias');
